#! /usr/bin/env python3

import os
import sys
import random

def create_process():
	pid = os.fork()
	if pid == 0:
		random_num = random.randint(5,10)
		minion_program = './minion'
		os.execv(minion_program, [minion_program, str(random_num)])
	else:
		print(f'Gru[{os.getpid()}]: process created. PID {pid}.')


n = int(sys.argv[1])
for i in range(n):
	create_process()

i = 0
while i < n:
	pid, status = os.wait()
	print(f'Gru[{os.getpid()}]: process terminated. PID {pid}. Exit status {os.WEXITSTATUS(status)}.')
	if status == 0:
		i += 1
	else:
		create_process()
