#! /usr/bin/env python3

import os
import sys
import time
import random

print(f'Minion[{os.getpid()}]: created. Parent PID {os.getppid()}.')
s = sys.argv[1]
time.sleep(int(s))
exit_status = random.randint(0, 1)
print(f'Child[{os.getpid()}]:  before terminated. Parent PID {os.getppid()}. Exit status {exit_status}.')
os._exit(exit_status)
