#! /usr/bin/env python3

import socket
import sys

BUFFER_SIZE = 1024
ENCODING = "utf-8"

def main():
	server_ip = sys.argv[1]
	server_port = int(sys.argv[2])

	client_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	client_sock.connect((server_ip, server_port))

	data = client_sock.recv(BUFFER_SIZE).decode(ENCODING)
	print(data)

	client_sock.close()

if __name__ == "__main__":
	main()

