#! /usr/bin/env python3

import socket
import sys
from datetime import datetime

HOST = "0.0.0.0"
BACKLOG = 1
BUFFER_SIZE = 1024
TIME_FORMAT = "%d.%m.%Y %H:%M"
ENCODING = "utf-8"

def main():
	port = int(sys.argv[1])

	server_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	server_sock.bind((HOST, port))
	server_sock.listen(BACKLOG)

	while True:
		client_sock, _ = server_sock.accept()
		now = datetime.now().strftime(TIME_FORMAT)
		client_sock.sendall(now.encode(ENCODING))
		client_sock.close()

if __name__ == "__main__":
	main()
